// Styles for Web Component Dev Tools

function getPositionStyles(position: string, isPanel: boolean = false): string {
  const offset = isPanel ? '70px' : '20px';

  switch (position) {
    case 'top-left':
      return isPanel ? `top: ${offset}; left: 20px;` : `top: 20px; left: 20px;`;
    case 'top-right':
      return isPanel ? `top: ${offset}; right: 20px;` : `top: 20px; right: 20px;`;
    case 'bottom-left':
      return isPanel ? `bottom: ${offset}; left: 20px;` : `bottom: 20px; left: 20px;`;
    case 'bottom-right':
    default:
      return isPanel ? `bottom: ${offset}; right: 20px;` : `bottom: 20px; right: 20px;`;
  }
}

export function injectStyles(position: string): void {
  const css = [
    '#wc-devtools-btn {',
    '  position: fixed;',
    `  ${getPositionStyles(position)}`,
    '  width: 50px;',
    '  height: 50px;',
    '  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
    '  border: none;',
    '  border-radius: 50%;',
    '  cursor: grab;',
    '  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);',
    '  z-index: 999999;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  transition: transform 0.3s ease, box-shadow 0.3s ease;',
    '  font-size: 24px;',
    '  color: white;',
    '  user-select: none;',
    '}',
    '',
    '#wc-devtools-btn:hover {',
    '  transform: scale(1.1);',
    '  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.4);',
    '}',
    '',
    '#wc-devtools-btn:active {',
    '  cursor: grabbing;',
    '}',
    '',
    '#wc-devtools-panel {',
    '  position: fixed;',
    `  ${getPositionStyles(position, true)}`,
    '  width: 500px;',
    '  max-height: 700px;',
    '  background: white;',
    '  border-radius: 12px;',
    '  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);',
    '  z-index: 999998;',
    '  display: none;',
    '  flex-direction: column;',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;',
    '  overflow: hidden;',
    '  transition: left 0.2s ease, top 0.2s ease;',
    '}',
    '',
    '#wc-devtools-panel.visible {',
    '  display: flex;',
    '}',
    '',
    '.wc-devtools-header {',
    '  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
    '  color: white;',
    '  padding: 16px;',
    '  font-weight: 600;',
    '  font-size: 16px;',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '}',
    '',
    '.wc-devtools-close {',
    '  background: none;',
    '  border: none;',
    '  color: white;',
    '  font-size: 24px;',
    '  cursor: pointer;',
    '  padding: 0;',
    '  width: 30px;',
    '  height: 30px;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  border-radius: 4px;',
    '  transition: background 0.2s;',
    '}',
    '',
    '.wc-devtools-close:hover {',
    '  background: rgba(255, 255, 255, 0.2);',
    '}',
    '',
    '.wc-devtools-search {',
    '  padding: 12px 16px;',
    '  background: #f7fafc;',
    '  border-bottom: 1px solid #e2e8f0;',
    '}',
    '',
    '.wc-devtools-search input {',
    '  width: 100%;',
    '  padding: 8px 12px;',
    '  border: 1px solid #cbd5e0;',
    '  border-radius: 6px;',
    '  font-size: 14px;',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;',
    '  outline: none;',
    '  transition: border-color 0.2s, box-shadow 0.2s;',
    '}',
    '',
    '.wc-devtools-search input:focus {',
    '  border-color: #667eea;',
    '  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);',
    '}',
    '',
    '.wc-devtools-search input::placeholder {',
    '  color: #a0aec0;',
    '}',
    '',
    '.wc-devtools-content {',
    '  padding: 16px;',
    '  overflow-y: auto;',
    '  flex: 1;',
    '}',
    '',
    '.wc-component {',
    '  background: #f7fafc;',
    '  border: 1px solid #e2e8f0;',
    '  border-radius: 8px;',
    '  padding: 12px;',
    '  margin-bottom: 12px;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.wc-component:hover {',
    '  border-color: #667eea;',
    '  box-shadow: 0 2px 8px rgba(102, 126, 234, 0.15);',
    '  transform: translateY(-1px);',
    '}',
    '',
    '.wc-instance-header {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  margin-bottom: 0;',
    '  padding: 4px;',
    '  border-radius: 4px;',
    '  transition: background 0.2s;',
    '}',
    '',
    '.wc-instance-header:hover {',
    '  background: rgba(102, 126, 234, 0.05);',
    '}',
    '',
    '.wc-instance-badge {',
    '  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
    '  color: white;',
    '  padding: 2px 8px;',
    '  border-radius: 12px;',
    '  font-weight: 600;',
    '  font-size: 11px;',
    '  margin-right: 8px;',
    '}',
    '',
    '.wc-component-name {',
    '  font-weight: 600;',
    '  color: #2d3748;',
    '  font-size: 14px;',
    '  display: flex;',
    '  align-items: center;',
    '  flex: 1;',
    '}',
    '',
    '.wc-expand-indicator {',
    '  color: #718096;',
    '  font-size: 18px;',
    '  margin-left: 8px;',
    '  transition: transform 0.2s;',
    '  user-select: none;',
    '}',
    '',
    '.wc-component.expanded .wc-expand-indicator {',
    '  transform: rotate(90deg);',
    '}',
    '',
    '.wc-component-details {',
    '  max-height: 0;',
    '  overflow: hidden;',
    '  transition: max-height 0.3s ease;',
    '}',
    '',
    '.wc-component.expanded .wc-component-details {',
    '  max-height: 2000px;',
    '}',
    '',
    '.wc-section {',
    '  margin-top: 12px;',
    '  padding-top: 8px;',
    '  border-top: 1px solid #e2e8f0;',
    '}',
    '',
    '.wc-section-title {',
    '  font-weight: 600;',
    '  font-size: 12px;',
    '  color: #4a5568;',
    '  margin-bottom: 6px;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '}',
    '',
    '.wc-component-attributes {',
    '  font-size: 12px;',
    '  color: #4a5568;',
    '}',
    '',
    '.wc-attribute {',
    '  background: white;',
    '  padding: 4px 8px;',
    '  border-radius: 4px;',
    '  margin: 4px 4px 4px 0;',
    '  display: inline-block;',
    '  border: 1px solid #e2e8f0;',
    '}',
    '',
    '.wc-attribute-name {',
    '  color: #805ad5;',
    '  font-weight: 500;',
    '}',
    '',
    '.wc-attribute-value {',
    '  color: #2d3748;',
    '}',
    '',
    '.wc-property {',
    '  background: white;',
    '  padding: 6px 10px;',
    '  border-radius: 4px;',
    '  margin: 4px 0;',
    '  border: 1px solid #e2e8f0;',
    '  font-size: 12px;',
    '}',
    '',
    '.wc-property-name {',
    '  color: #3182ce;',
    '  font-weight: 500;',
    '}',
    '',
    '.wc-property-value {',
    '  color: #2d3748;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '}',
    '',
    '.wc-property-type {',
    '  color: #718096;',
    '  font-style: italic;',
    '  font-size: 11px;',
    '}',
    '',
    '.wc-method {',
    '  background: white;',
    '  padding: 4px 8px;',
    '  border-radius: 4px;',
    '  margin: 4px 4px 4px 0;',
    '  display: inline-block;',
    '  border: 1px solid #e2e8f0;',
    '  font-size: 12px;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '}',
    '',
    '.wc-method-name {',
    '  color: #d69e2e;',
    '  font-weight: 500;',
    '}',
    '',
    '.wc-slot {',
    '  background: white;',
    '  padding: 4px 8px;',
    '  border-radius: 4px;',
    '  margin: 4px 4px 4px 0;',
    '  display: inline-block;',
    '  border: 1px solid #e2e8f0;',
    '  font-size: 12px;',
    '}',
    '',
    '.wc-slot-name {',
    '  color: #38a169;',
    '  font-weight: 500;',
    '}',
    '',
    '.wc-slot-status {',
    '  color: #718096;',
    '  font-size: 11px;',
    '}',
    '',
    '.wc-slot.has-content {',
    '  border-color: #38a169;',
    '  background: #f0fff4;',
    '}',
    '',
    '.wc-no-components {',
    '  text-align: center;',
    '  color: #718096;',
    '  padding: 32px;',
    '}',
    '',
    '.wc-stats {',
    '  background: #edf2f7;',
    '  padding: 12px;',
    '  border-radius: 8px;',
    '  margin-bottom: 16px;',
    '  font-size: 14px;',
    '  color: #2d3748;',
    '}',
    '',
    '.wc-element-highlight {',
    '  outline: 3px solid #667eea !important;',
    '  outline-offset: 4px !important;',
    '  background: rgba(102, 126, 234, 0.2) !important;',
    '  box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.3), 0 0 20px rgba(102, 126, 234, 0.4) !important;',
    '  position: relative !important;',
    '  z-index: 999997 !important;',
    '  animation: wc-highlight-pulse 0.6s ease-in-out 3 !important;',
    '}',
    '',
    '@keyframes wc-highlight-pulse {',
    '  0%, 100% {',
    '    outline-width: 3px;',
    '    outline-offset: 4px;',
    '    box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.3), 0 0 20px rgba(102, 126, 234, 0.4);',
    '  }',
    '  50% {',
    '    outline-width: 5px;',
    '    outline-offset: 6px;',
    '    box-shadow: 0 0 0 8px rgba(102, 126, 234, 0.4), 0 0 30px rgba(102, 126, 234, 0.6);',
    '  }',
    '}',
    '',
    '.wc-locate-btn {',
    '  background: #667eea;',
    '  color: white;',
    '  border: none;',
    '  border-radius: 4px;',
    '  padding: 6px;',
    '  cursor: pointer;',
    '  transition: all 0.2s ease;',
    '  margin-right: 8px;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: 24px;',
    '  height: 24px;',
    '}',
    '',
    '.wc-locate-btn:hover {',
    '  background: #5568d3;',
    '  transform: scale(1.1);',
    '}',
    '',
    '.wc-locate-btn svg {',
    '  width: 14px;',
    '  height: 14px;',
    '}',
    '',
    '.wc-devtools-tabs {',
    '  display: flex;',
    '  background: #f7fafc;',
    '  border-bottom: 2px solid #e2e8f0;',
    '}',
    '',
    '.wc-devtools-tab {',
    '  flex: 1;',
    '  padding: 12px 16px;',
    '  background: none;',
    '  border: none;',
    '  font-size: 14px;',
    '  font-weight: 500;',
    '  color: #718096;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '  border-bottom: 2px solid transparent;',
    '  margin-bottom: -2px;',
    '}',
    '',
    '.wc-devtools-tab:hover {',
    '  color: #667eea;',
    '  background: rgba(102, 126, 234, 0.05);',
    '}',
    '',
    '.wc-devtools-tab.active {',
    '  color: #667eea;',
    '  border-bottom-color: #667eea;',
    '  background: white;',
    '}',
    '',
    '.wc-devtools-tab-content {',
    '  display: none;',
    '}',
    '',
    '.wc-devtools-tab-content.active {',
    '  display: block;',
    '}',
    '',
    '.wc-events-controls {',
    '  display: flex;',
    '  gap: 8px;',
    '  padding: 12px 16px;',
    '  background: #f7fafc;',
    '  border-bottom: 1px solid #e2e8f0;',
    '}',
    '',
    '.wc-events-toggle {',
    '  flex: 1;',
    '  padding: 8px 16px;',
    '  background: #667eea;',
    '  color: white;',
    '  border: none;',
    '  border-radius: 6px;',
    '  font-size: 14px;',
    '  font-weight: 500;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '}',
    '',
    '.wc-events-toggle:hover {',
    '  background: #5568d3;',
    '}',
    '',
    '.wc-events-toggle.monitoring {',
    '  background: #48bb78;',
    '}',
    '',
    '.wc-events-toggle.monitoring:hover {',
    '  background: #38a169;',
    '}',
    '',
    '.wc-events-clear {',
    '  padding: 8px 16px;',
    '  background: #e2e8f0;',
    '  color: #2d3748;',
    '  border: none;',
    '  border-radius: 6px;',
    '  font-size: 14px;',
    '  font-weight: 500;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '}',
    '',
    '.wc-events-clear:hover {',
    '  background: #cbd5e0;',
    '}',
    '',
    '.wc-event-log {',
    '  background: #f7fafc;',
    '  border: 1px solid #e2e8f0;',
    '  border-radius: 8px;',
    '  padding: 12px;',
    '  margin-bottom: 8px;',
    '  font-size: 12px;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.wc-event-log:hover {',
    '  border-color: #667eea;',
    '  box-shadow: 0 2px 8px rgba(102, 126, 234, 0.15);',
    '}',
    '',
    '.wc-event-header {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  margin-bottom: 6px;',
    '}',
    '',
    '.wc-event-type {',
    '  font-weight: 600;',
    '  color: #667eea;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '}',
    '',
    '.wc-event-timestamp {',
    '  color: #718096;',
    '  font-size: 11px;',
    '}',
    '',
    '.wc-event-source {',
    '  color: #805ad5;',
    '  font-weight: 500;',
    '  margin-bottom: 4px;',
    '}',
    '',
    '.wc-event-detail {',
    '  background: white;',
    '  padding: 8px;',
    '  border-radius: 4px;',
    '  border: 1px solid #e2e8f0;',
    '  color: #2d3748;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  white-space: pre-wrap;',
    '  word-break: break-word;',
    '  max-height: 200px;',
    '  overflow-y: auto;',
    '}',
    '',
    '.wc-no-events {',
    '  text-align: center;',
    '  color: #718096;',
    '  padding: 32px;',
    '}',
  ].join('\n');

  const styleEl = document.createElement('style');
  styleEl.textContent = css;
  document.head.appendChild(styleEl);
}
