// Styles for Web Component Dev Tools

function getPositionStyles(position: string, isPanel: boolean = false): string {
  const offset = isPanel ? '70px' : '20px';

  switch (position) {
    case 'top-left':
      return isPanel ? `top: ${offset}; left: 20px;` : `top: 20px; left: 20px;`;
    case 'top-right':
      return isPanel ? `top: ${offset}; right: 20px;` : `top: 20px; right: 20px;`;
    case 'bottom-left':
      return isPanel ? `bottom: ${offset}; left: 20px;` : `bottom: 20px; left: 20px;`;
    case 'bottom-right':
    default:
      return isPanel ? `bottom: ${offset}; right: 20px;` : `bottom: 20px; right: 20px;`;
  }
}

export function injectStyles(position: string): void {
  const css = [
    '#wc-devtools-btn {',
    '  position: fixed;',
    `  ${getPositionStyles(position)}`,
    '  width: 50px;',
    '  height: 50px;',
    '  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
    '  border: none;',
    '  border-radius: 50%;',
    '  cursor: grab;',
    '  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);',
    '  z-index: 999999;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  transition: transform 0.3s ease, box-shadow 0.3s ease;',
    '  font-size: 24px;',
    '  color: white;',
    '  user-select: none;',
    '}',
    '',
    '#wc-devtools-btn:hover {',
    '  transform: scale(1.1);',
    '  box-shadow: 0 6px 16px rgba(0, 0, 0, 0.4);',
    '}',
    '',
    '#wc-devtools-btn:active {',
    '  cursor: grabbing;',
    '}',
    '',
    '#wc-devtools-panel {',
    '  position: fixed;',
    `  ${getPositionStyles(position, true)}`,
    '  width: 500px;',
    '  max-height: 700px;',
    '  background: white;',
    '  border-radius: 12px;',
    '  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);',
    '  z-index: 999998;',
    '  display: none;',
    '  flex-direction: column;',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;',
    '  overflow: hidden;',
    '  transition: left 0.2s ease, top 0.2s ease;',
    '}',
    '',
    '#wc-devtools-panel.visible {',
    '  display: flex;',
    '}',
    '',
    '.wc-devtools-header {',
    '  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
    '  color: white;',
    '  padding: 16px;',
    '  font-weight: 600;',
    '  font-size: 16px;',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '}',
    '',
    '.wc-devtools-close {',
    '  background: none;',
    '  border: none;',
    '  color: white;',
    '  font-size: 24px;',
    '  cursor: pointer;',
    '  padding: 0;',
    '  width: 30px;',
    '  height: 30px;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  border-radius: 4px;',
    '  transition: background 0.2s;',
    '}',
    '',
    '.wc-devtools-close:hover {',
    '  background: rgba(255, 255, 255, 0.2);',
    '}',
    '',
    '.wc-devtools-search {',
    '  padding: 12px 16px;',
    '  background: #f7fafc;',
    '  border-bottom: 1px solid #e2e8f0;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 12px;',
    '}',
    '',
    '.wc-devtools-search input {',
    '  flex: 1;',
    '  padding: 8px 12px;',
    '  border: 1px solid #cbd5e0;',
    '  border-radius: 6px;',
    '  font-size: 14px;',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;',
    '  outline: none;',
    '  transition: border-color 0.2s, box-shadow 0.2s;',
    '}',
    '',
    '.wc-devtools-search input:focus {',
    '  border-color: #667eea;',
    '  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);',
    '}',
    '',
    '.wc-devtools-search input::placeholder {',
    '  color: #a0aec0;',
    '}',
    '',
    '.wc-devtools-content {',
    '  padding: 16px;',
    '  overflow-y: auto;',
    '  flex: 1;',
    '}',
    '',
    '.wc-component {',
    '  background: #f7fafc;',
    '  border: 1px solid #e2e8f0;',
    '  border-radius: 8px;',
    '  padding: 12px;',
    '  margin-bottom: 12px;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.wc-component:hover {',
    '  border-color: #667eea;',
    '  box-shadow: 0 2px 8px rgba(102, 126, 234, 0.15);',
    '  transform: translateY(-1px);',
    '}',
    '',
    '.wc-instance-header {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  margin-bottom: 0;',
    '  padding: 4px;',
    '  border-radius: 4px;',
    '  transition: background 0.2s;',
    '}',
    '',
    '.wc-instance-header:hover {',
    '  background: rgba(102, 126, 234, 0.05);',
    '}',
    '',
    '.wc-instance-badge {',
    '  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
    '  color: white;',
    '  padding: 2px 8px;',
    '  border-radius: 12px;',
    '  font-weight: 600;',
    '  font-size: 11px;',
    '  margin-right: 8px;',
    '}',
    '',
    '.wc-component-name {',
    '  font-weight: 600;',
    '  color: #2d3748;',
    '  font-size: 14px;',
    '  display: flex;',
    '  align-items: center;',
    '  flex: 1;',
    '}',
    '',
    '.wc-expand-indicator {',
    '  color: #718096;',
    '  font-size: 18px;',
    '  margin-left: 8px;',
    '  transition: transform 0.2s;',
    '  user-select: none;',
    '}',
    '',
    '.wc-component.expanded .wc-expand-indicator {',
    '  transform: rotate(90deg);',
    '}',
    '',
    '.wc-component-details {',
    '  max-height: 0;',
    '  overflow: hidden;',
    '  transition: max-height 0.3s ease;',
    '}',
    '',
    '.wc-component.expanded .wc-component-details {',
    '  max-height: 2000px;',
    '}',
    '',
    '.wc-section {',
    '  margin-top: 12px;',
    '  padding-top: 8px;',
    '  border-top: 1px solid #e2e8f0;',
    '}',
    '',
    '.wc-section-title {',
    '  font-weight: 600;',
    '  font-size: 12px;',
    '  color: #4a5568;',
    '  margin-bottom: 6px;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '}',
    '',
    '.wc-component-attributes {',
    '  font-size: 12px;',
    '  color: #4a5568;',
    '}',
    '',
    '.wc-attribute {',
    '  background: white;',
    '  padding: 4px 8px;',
    '  border-radius: 4px;',
    '  margin: 4px 4px 4px 0;',
    '  display: inline-block;',
    '  border: 1px solid #e2e8f0;',
    '}',
    '',
    '.wc-attribute-name {',
    '  color: #805ad5;',
    '  font-weight: 500;',
    '}',
    '',
    '.wc-attribute-value {',
    '  color: #2d3748;',
    '}',
    '',
    '.wc-property {',
    '  background: white;',
    '  padding: 6px 10px;',
    '  border-radius: 4px;',
    '  margin: 4px 0;',
    '  border: 1px solid #e2e8f0;',
    '  font-size: 12px;',
    '}',
    '',
    '.wc-property-name {',
    '  color: #3182ce;',
    '  font-weight: 500;',
    '}',
    '',
    '.wc-property-value {',
    '  color: #2d3748;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '}',
    '',
    '.wc-property-type {',
    '  color: #718096;',
    '  font-style: italic;',
    '  font-size: 11px;',
    '}',
    '',
    '.wc-method {',
    '  background: white;',
    '  padding: 4px 8px;',
    '  border-radius: 4px;',
    '  margin: 4px 4px 4px 0;',
    '  display: inline-block;',
    '  border: 1px solid #e2e8f0;',
    '  font-size: 12px;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '}',
    '',
    '.wc-method-name {',
    '  color: #d69e2e;',
    '  font-weight: 500;',
    '}',
    '',
    '.wc-slot {',
    '  background: white;',
    '  padding: 4px 8px;',
    '  border-radius: 4px;',
    '  margin: 4px 4px 4px 0;',
    '  display: inline-block;',
    '  border: 1px solid #e2e8f0;',
    '  font-size: 12px;',
    '}',
    '',
    '.wc-slot-name {',
    '  color: #38a169;',
    '  font-weight: 500;',
    '}',
    '',
    '.wc-slot-status {',
    '  color: #718096;',
    '  font-size: 11px;',
    '}',
    '',
    '.wc-slot.has-content {',
    '  border-color: #38a169;',
    '  background: #f0fff4;',
    '}',
    '',
    '.wc-slot-detail {',
    '  margin-bottom: 8px;',
    '}',
    '',
    '.wc-slot-assigned-inline {',
    '  padding-left: 20px;',
    '  margin-top: 4px;',
    '  font-size: 11px;',
    '}',
    '',
    '.wc-slot-assigned-tag {',
    '  background: #edf2f7;',
    '  padding: 2px 6px;',
    '  border-radius: 3px;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  color: #2d3748;',
    '  border: 1px solid #cbd5e0;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.wc-slot-assigned-tag:hover {',
    '  background: #667eea;',
    '  color: white;',
    '  border-color: #667eea;',
    '  transform: translateY(-1px);',
    '}',
    '',
    '.wc-no-components {',
    '  text-align: center;',
    '  color: #718096;',
    '  padding: 32px;',
    '}',
    '',
    '.wc-stats {',
    '  background: #edf2f7;',
    '  padding: 12px;',
    '  border-radius: 8px;',
    '  margin-bottom: 16px;',
    '  font-size: 14px;',
    '  color: #2d3748;',
    '}',
    '',
    '.wc-element-highlight {',
    '  outline: 3px solid #667eea !important;',
    '  outline-offset: 4px !important;',
    '  background: rgba(102, 126, 234, 0.2) !important;',
    '  box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.3), 0 0 20px rgba(102, 126, 234, 0.4) !important;',
    '  position: relative !important;',
    '  z-index: 999997 !important;',
    '  animation: wc-highlight-pulse 0.6s ease-in-out 3 !important;',
    '}',
    '',
    '@keyframes wc-highlight-pulse {',
    '  0%, 100% {',
    '    outline-width: 3px;',
    '    outline-offset: 4px;',
    '    box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.3), 0 0 20px rgba(102, 126, 234, 0.4);',
    '  }',
    '  50% {',
    '    outline-width: 5px;',
    '    outline-offset: 6px;',
    '    box-shadow: 0 0 0 8px rgba(102, 126, 234, 0.4), 0 0 30px rgba(102, 126, 234, 0.6);',
    '  }',
    '}',
    '',
    '.wc-locate-btn {',
    '  background: #667eea;',
    '  color: white;',
    '  border: none;',
    '  border-radius: 4px;',
    '  padding: 6px;',
    '  cursor: pointer;',
    '  transition: all 0.2s ease;',
    '  margin-right: 8px;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: 24px;',
    '  height: 24px;',
    '}',
    '',
    '.wc-locate-btn:hover {',
    '  background: #5568d3;',
    '  transform: scale(1.1);',
    '}',
    '',
    '.wc-locate-btn svg {',
    '  width: 14px;',
    '  height: 14px;',
    '}',
    '',
    '.wc-devtools-tabs {',
    '  display: flex;',
    '  background: #f7fafc;',
    '  border-bottom: 2px solid #e2e8f0;',
    '}',
    '',
    '.wc-devtools-tab {',
    '  flex: 1;',
    '  padding: 12px 16px;',
    '  background: none;',
    '  border: none;',
    '  font-size: 14px;',
    '  font-weight: 500;',
    '  color: #718096;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '  border-bottom: 2px solid transparent;',
    '  margin-bottom: -2px;',
    '}',
    '',
    '.wc-devtools-tab:hover {',
    '  color: #667eea;',
    '  background: rgba(102, 126, 234, 0.05);',
    '}',
    '',
    '.wc-devtools-tab.active {',
    '  color: #667eea;',
    '  border-bottom-color: #667eea;',
    '  background: white;',
    '}',
    '',
    '.wc-devtools-tab-content {',
    '  display: none;',
    '}',
    '',
    '.wc-devtools-tab-content.active {',
    '  display: block;',
    '}',
    '',
    '.wc-events-controls {',
    '  display: flex;',
    '  gap: 8px;',
    '  padding: 12px 16px;',
    '  background: #f7fafc;',
    '  border-bottom: 1px solid #e2e8f0;',
    '}',
    '',
    '.wc-events-toggle {',
    '  flex: 1;',
    '  padding: 8px 16px;',
    '  background: #667eea;',
    '  color: white;',
    '  border: none;',
    '  border-radius: 6px;',
    '  font-size: 14px;',
    '  font-weight: 500;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '}',
    '',
    '.wc-events-toggle:hover {',
    '  background: #5568d3;',
    '}',
    '',
    '.wc-events-toggle.monitoring {',
    '  background: #48bb78;',
    '}',
    '',
    '.wc-events-toggle.monitoring:hover {',
    '  background: #38a169;',
    '}',
    '',
    '.wc-events-clear {',
    '  padding: 8px 16px;',
    '  background: #e2e8f0;',
    '  color: #2d3748;',
    '  border: none;',
    '  border-radius: 6px;',
    '  font-size: 14px;',
    '  font-weight: 500;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '}',
    '',
    '.wc-events-clear:hover {',
    '  background: #cbd5e0;',
    '}',
    '',
    '.wc-event-log {',
    '  background: #f7fafc;',
    '  border: 1px solid #e2e8f0;',
    '  border-radius: 8px;',
    '  padding: 12px;',
    '  margin-bottom: 8px;',
    '  font-size: 12px;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.wc-event-log:hover {',
    '  border-color: #667eea;',
    '  box-shadow: 0 2px 8px rgba(102, 126, 234, 0.15);',
    '}',
    '',
    '.wc-event-header {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  margin-bottom: 6px;',
    '}',
    '',
    '.wc-event-type {',
    '  font-weight: 600;',
    '  color: #667eea;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '}',
    '',
    '.wc-event-timestamp {',
    '  color: #718096;',
    '  font-size: 11px;',
    '}',
    '',
    '.wc-event-source {',
    '  color: #805ad5;',
    '  font-weight: 500;',
    '  margin-bottom: 4px;',
    '}',
    '',
    '.wc-event-detail {',
    '  background: white;',
    '  padding: 8px;',
    '  border-radius: 4px;',
    '  border: 1px solid #e2e8f0;',
    '  color: #2d3748;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  white-space: pre-wrap;',
    '  word-break: break-word;',
    '  max-height: 200px;',
    '  overflow-y: auto;',
    '}',
    '',
    '.wc-no-events {',
    '  text-align: center;',
    '  color: #718096;',
    '  padding: 32px;',
    '}',
    '',
    '/* Undo/Redo Controls */',
    '.wc-undo-redo-controls {',
    '  display: flex;',
    '  gap: 4px;',
    '  margin-left: auto;',
    '}',
    '',
    '.wc-undo-btn,',
    '.wc-redo-btn {',
    '  background: white;',
    '  border: 1px solid #e2e8f0;',
    '  border-radius: 4px;',
    '  padding: 6px;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: 28px;',
    '  height: 28px;',
    '}',
    '',
    '.wc-undo-btn:hover:not(:disabled),',
    '.wc-redo-btn:hover:not(:disabled) {',
    '  background: #f7fafc;',
    '  border-color: #667eea;',
    '  transform: scale(1.05);',
    '}',
    '',
    '.wc-undo-btn:disabled,',
    '.wc-redo-btn:disabled {',
    '  opacity: 0.4;',
    '  cursor: not-allowed;',
    '}',
    '',
    '.wc-undo-btn svg,',
    '.wc-redo-btn svg {',
    '  width: 16px;',
    '  height: 16px;',
    '  color: #667eea;',
    '}',
    '',
    '/* Editable Attributes and Properties */',
    '.wc-editable-attr,',
    '.wc-editable-prop {',
    '  position: relative;',
    '}',
    '',
    '.wc-editable-value-container {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '  padding: 2px 6px;',
    '  border-radius: 4px;',
    '  transition: all 0.2s;',
    '}',
    '',
    '.wc-editable-value-container:hover {',
    '  background: rgba(102, 126, 234, 0.1);',
    '}',
    '',
    '.wc-editable-value {',
    '  transition: all 0.2s;',
    '}',
    '',
    '.wc-edit-icon {',
    '  color: #667eea;',
    '  font-size: 12px;',
    '  opacity: 0;',
    '  transition: opacity 0.2s;',
    '}',
    '',
    '.wc-editable-value-container:hover .wc-edit-icon {',
    '  opacity: 1;',
    '}',
    '',
    '.wc-inline-editor {',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  font-size: 13px;',
    '  padding: 4px 8px;',
    '  border: 2px solid #667eea;',
    '  border-radius: 4px;',
    '  outline: none;',
    '  background: white;',
    '  color: #2d3748;',
    '  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.2);',
    '}',
    '',
    '.wc-inline-editor.error {',
    '  border-color: #e53e3e;',
    '  box-shadow: 0 0 0 3px rgba(229, 62, 62, 0.2);',
    '}',
    '',
    '.wc-inline-editor:focus {',
    '  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.3);',
    '}',
    '',
    '.wc-edit-error {',
    '  position: absolute;',
    '  top: 100%;',
    '  left: 0;',
    '  margin-top: 4px;',
    '  padding: 4px 8px;',
    '  background: #fed7d7;',
    '  color: #c53030;',
    '  border: 1px solid #fc8181;',
    '  border-radius: 4px;',
    '  font-size: 11px;',
    '  z-index: 1000;',
    '  white-space: nowrap;',
    '  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);',
    '}',
    '',
    '/* Shadow DOM Visualization */',
    '.wc-shadow-info {',
    '  font-size: 12px;',
    '  color: #4a5568;',
    '  margin-bottom: 8px;',
    '}',
    '',
    '.wc-shadow-mode {',
    '  background: #e6fffa;',
    '  color: #234e52;',
    '  padding: 4px 8px;',
    '  border-radius: 4px;',
    '  font-weight: 500;',
    '  border: 1px solid #81e6d9;',
    '}',
    '',
    '.wc-shadow-stylesheets {',
    '  color: #718096;',
    '  margin-left: 8px;',
    '}',
    '',
    '.wc-shadow-subsection-title {',
    '  font-weight: 600;',
    '  font-size: 11px;',
    '  color: #2d3748;',
    '  margin-top: 8px;',
    '  margin-bottom: 6px;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '}',
    '',
    '.wc-shadow-custom-props {',
    '  margin-top: 8px;',
    '}',
    '',
    '.wc-shadow-custom-prop {',
    '  background: white;',
    '  padding: 6px 10px;',
    '  border-radius: 4px;',
    '  margin: 4px 0;',
    '  border: 1px solid #e2e8f0;',
    '  font-size: 12px;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '}',
    '',
    '.wc-shadow-prop-name {',
    '  color: #9f7aea;',
    '  font-weight: 600;',
    '}',
    '',
    '.wc-shadow-prop-value {',
    '  color: #2d3748;',
    '}',
    '',
    '.wc-shadow-slots {',
    '  margin-top: 8px;',
    '}',
    '',
    '.wc-slot-assignment {',
    '  background: white;',
    '  border: 1px solid #e2e8f0;',
    '  border-radius: 4px;',
    '  padding: 8px;',
    '  margin: 4px 0;',
    '  font-size: 12px;',
    '}',
    '',
    '.wc-slot-assignment.has-content {',
    '  border-color: #38a169;',
    '  background: #f0fff4;',
    '}',
    '',
    '.wc-slot-assignment-header {',
    '  font-weight: 600;',
    '  margin-bottom: 6px;',
    '}',
    '',
    '.wc-slot-assignment-name {',
    '  color: #38a169;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '}',
    '',
    '.wc-slot-assignment-count {',
    '  color: #718096;',
    '  font-weight: 400;',
    '}',
    '',
    '.wc-slot-assigned-elements {',
    '  padding-left: 12px;',
    '}',
    '',
    '.wc-slot-assigned-element {',
    '  background: #edf2f7;',
    '  padding: 4px 8px;',
    '  border-radius: 3px;',
    '  margin: 2px 0;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  color: #2d3748;',
    '  font-size: 11px;',
    '  border-left: 3px solid #38a169;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.wc-slot-assigned-element:hover {',
    '  background: #667eea;',
    '  color: white;',
    '  border-left-color: #5568d3;',
    '  transform: translateX(2px);',
    '}',
    '',
    '.wc-shadow-tree {',
    '  margin-top: 8px;',
    '}',
    '',
    '.wc-shadow-tree-container {',
    '  background: white;',
    '  border: 1px solid #e2e8f0;',
    '  border-radius: 4px;',
    '  padding: 8px;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  font-size: 12px;',
    '  max-height: 400px;',
    '  overflow-y: auto;',
    '}',
    '',
    '.wc-shadow-node {',
    '  margin: 2px 0;',
    '}',
    '',
    '.wc-shadow-node-header {',
    '  display: flex;',
    '  align-items: center;',
    '  padding: 2px 4px;',
    '  border-radius: 3px;',
    '  transition: background 0.2s;',
    '}',
    '',
    '.wc-shadow-node-header:hover {',
    '  background: #f7fafc;',
    '}',
    '',
    '.wc-shadow-node-expand {',
    '  cursor: pointer;',
    '  color: #718096;',
    '  font-size: 10px;',
    '  width: 12px;',
    '  display: inline-block;',
    '  transition: transform 0.2s;',
    '  user-select: none;',
    '}',
    '',
    '.wc-shadow-node-expandable.expanded .wc-shadow-node-expand {',
    '  transform: rotate(90deg);',
    '}',
    '',
    '.wc-shadow-node-spacer {',
    '  width: 12px;',
    '  display: inline-block;',
    '}',
    '',
    '.wc-shadow-node-tag {',
    '  color: #3182ce;',
    '  font-weight: 600;',
    '}',
    '',
    '.wc-shadow-node-tag.slot {',
    '  color: #38a169;',
    '  background: #f0fff4;',
    '  padding: 2px 4px;',
    '  border-radius: 3px;',
    '}',
    '',
    '.wc-shadow-node-attrs {',
    '  color: #805ad5;',
    '}',
    '',
    '.wc-shadow-node-children {',
    '  max-height: 0;',
    '  overflow: hidden;',
    '  transition: max-height 0.3s ease;',
    '}',
    '',
    '.wc-shadow-node-expandable.expanded .wc-shadow-node-children {',
    '  max-height: 2000px;',
    '}',
    '',
    '.wc-shadow-text-node {',
    '  color: #718096;',
    '  font-style: italic;',
    '  padding-left: 12px;',
    '}',
    '',
    '/* CSS Variables Styles */',
    '.wc-css-variables {',
    '  margin-top: 8px;',
    '}',
    '',
    '.wc-css-variable {',
    '  background: white;',
    '  border: 1px solid #e2e8f0;',
    '  border-radius: 4px;',
    '  padding: 8px;',
    '  margin: 4px 0;',
    '  font-size: 12px;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.wc-css-variable:hover {',
    '  border-color: #667eea;',
    '  box-shadow: 0 1px 3px rgba(102, 126, 234, 0.1);',
    '}',
    '',
    '.wc-css-variable-header {',
    '  display: flex;',
    '  align-items: flex-start;',
    '  gap: 8px;',
    '  margin-bottom: 6px;',
    '}',
    '',
    '.wc-css-variable-name {',
    '  color: #9f7aea;',
    '  font-weight: 600;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  flex-shrink: 0;',
    '}',
    '',
    '.wc-css-variable-value {',
    '  color: #2d3748;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  flex: 1;',
    '  word-break: break-word;',
    '}',
    '',
    '.wc-css-variable-computed {',
    '  color: #718096;',
    '  font-size: 11px;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  margin-top: 4px;',
    '  padding-left: 16px;',
    '}',
    '',
    '.wc-css-variable-meta {',
    '  display: flex;',
    '  gap: 8px;',
    '  margin-top: 6px;',
    '  flex-wrap: wrap;',
    '}',
    '',
    '.wc-css-variable-source {',
    '  display: inline-block;',
    '  padding: 2px 6px;',
    '  border-radius: 3px;',
    '  font-size: 10px;',
    '  font-weight: 600;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '}',
    '',
    '.wc-css-variable-source.element {',
    '  background: #bee3f8;',
    '  color: #2c5282;',
    '}',
    '',
    '.wc-css-variable-source.shadow-root {',
    '  background: #d6bcfa;',
    '  color: #553c9a;',
    '}',
    '',
    '.wc-css-variable-source.inherited {',
    '  background: #fed7d7;',
    '  color: #9b2c2c;',
    '}',
    '',
    '.wc-css-variable-source.root {',
    '  background: #c6f6d5;',
    '  color: #276749;',
    '}',
    '',
    '.wc-css-variable-selector {',
    '  color: #718096;',
    '  font-size: 10px;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  background: #f7fafc;',
    '  padding: 2px 6px;',
    '  border-radius: 3px;',
    '}',
    '',
    '.wc-css-variable-inherited-from {',
    '  color: #e53e3e;',
    '  font-size: 10px;',
    '  font-family: "Monaco", "Courier New", monospace;',
    '  background: #fff5f5;',
    '  padding: 2px 6px;',
    '  border-radius: 3px;',
    '}',
    '',
    '.wc-css-variable-editable {',
    '  cursor: pointer;',
    '}',
    '',
    '.wc-css-variable-editable .wc-css-variable-value {',
    '  border-bottom: 1px dashed #cbd5e0;',
    '  transition: border-color 0.2s;',
    '}',
    '',
    '.wc-css-variable-editable:hover .wc-css-variable-value {',
    '  border-bottom-color: #667eea;',
    '}',
    '',
    '.wc-css-variable-edit-icon {',
    '  color: #667eea;',
    '  font-size: 14px;',
    '  opacity: 0;',
    '  transition: opacity 0.2s;',
    '  cursor: pointer;',
    '}',
    '',
    '.wc-css-variable-editable:hover .wc-css-variable-edit-icon {',
    '  opacity: 1;',
    '}',
    '',
    '.wc-css-variable-empty {',
    '  text-align: center;',
    '  padding: 16px;',
    '  color: #a0aec0;',
    '  font-style: italic;',
    '  font-size: 12px;',
    '}',
    '',
    '/* Render Count Badge Styles */',
    '.wc-render-count-badge {',
    '  margin-left: 8px;',
    '  padding: 2px 8px;',
    '  background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);',
    '  color: white;',
    '  border-radius: 12px;',
    '  font-size: 10px;',
    '  font-weight: 600;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '  box-shadow: 0 2px 4px rgba(240, 147, 251, 0.3);',
    '  animation: pulse-render 2s ease-in-out infinite;',
    '}',
    '',
    '@keyframes pulse-render {',
    '  0%, 100% {',
    '    opacity: 1;',
    '    transform: scale(1);',
    '  }',
    '  50% {',
    '    opacity: 0.85;',
    '    transform: scale(1.02);',
    '  }',
    '}',
    '',
    '.wc-render-count-badge.wc-render-count-flash {',
    '  animation: flash-render 0.5s ease-in-out;',
    '}',
    '',
    '@keyframes flash-render {',
    '  0% {',
    '    transform: scale(1);',
    '    box-shadow: 0 2px 4px rgba(240, 147, 251, 0.3);',
    '  }',
    '  50% {',
    '    transform: scale(1.15);',
    '    box-shadow: 0 4px 12px rgba(240, 147, 251, 0.6);',
    '  }',
    '  100% {',
    '    transform: scale(1);',
    '    box-shadow: 0 2px 4px rgba(240, 147, 251, 0.3);',
    '  }',
    '}',
    '',
    '/* Render Tracking Toggle Button */',
    '.wc-render-tracking-toggle {',
    '  background: white;',
    '  border: 2px solid #e2e8f0;',
    '  border-radius: 6px;',
    '  width: 32px;',
    '  height: 32px;',
    '  padding: 4px;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  margin-left: 4px;',
    '}',
    '',
    '.wc-render-tracking-toggle:hover {',
    '  border-color: #667eea;',
    '  background: #f7fafc;',
    '  transform: translateY(-1px);',
    '}',
    '',
    '.wc-render-tracking-toggle svg {',
    '  width: 20px;',
    '  height: 20px;',
    '  color: #718096;',
    '}',
    '',
    '.wc-render-tracking-toggle.active {',
    '  background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);',
    '  border-color: #f5576c;',
    '}',
    '',
    '.wc-render-tracking-toggle.active svg {',
    '  color: white;',
    '}',
    '',
    '.wc-render-tracking-toggle:active {',
    '  transform: translateY(0);',
    '}',
    '',
    '/* On-Page Render Count Overlays */',
    '.wc-render-overlay {',
    '  position: fixed;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-width: 28px;',
    '  height: 28px;',
    '  padding: 4px 8px;',
    '  background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);',
    '  color: white;',
    '  border-radius: 14px;',
    '  font-size: 12px;',
    '  font-weight: 700;',
    '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;',
    '  box-shadow: 0 3px 8px rgba(245, 87, 108, 0.4), 0 0 0 2px white;',
    '  pointer-events: none;',
    '  z-index: 999997;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.wc-render-overlay.flash {',
    '  animation: flash-overlay 0.5s ease-out;',
    '}',
    '',
    '@keyframes flash-overlay {',
    '  0% {',
    '    transform: scale(1);',
    '    box-shadow: 0 3px 8px rgba(245, 87, 108, 0.4), 0 0 0 2px white;',
    '  }',
    '  50% {',
    '    transform: scale(1.3);',
    '    box-shadow: 0 5px 15px rgba(245, 87, 108, 0.8), 0 0 0 3px white, 0 0 20px rgba(245, 87, 108, 0.6);',
    '  }',
    '  100% {',
    '    transform: scale(1);',
    '    box-shadow: 0 3px 8px rgba(245, 87, 108, 0.4), 0 0 0 2px white;',
    '  }',
    '}',
    '',
    '#wc-render-overlay-container {',
    '  pointer-events: none;',
    '}',
    '',
    '/* Render Overlay Toggle Button */',
    '.wc-render-overlay-toggle {',
    '  background: white;',
    '  border: 2px solid #e2e8f0;',
    '  border-radius: 6px;',
    '  width: 32px;',
    '  height: 32px;',
    '  padding: 4px;',
    '  cursor: pointer;',
    '  transition: all 0.2s;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  margin-left: 4px;',
    '}',
    '',
    '.wc-render-overlay-toggle:hover {',
    '  border-color: #667eea;',
    '  background: #f7fafc;',
    '  transform: translateY(-1px);',
    '}',
    '',
    '.wc-render-overlay-toggle svg {',
    '  width: 20px;',
    '  height: 20px;',
    '  color: #718096;',
    '}',
    '',
    '.wc-render-overlay-toggle.active {',
    '  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
    '  border-color: #667eea;',
    '}',
    '',
    '.wc-render-overlay-toggle.active svg {',
    '  color: white;',
    '}',
    '',
    '.wc-render-overlay-toggle.active svg circle {',
    '  fill: white;',
    '}',
    '',
    '.wc-render-overlay-toggle:active {',
    '  transform: translateY(0);',
    '}',
  ].join('\n');

  const styleEl = document.createElement('style');
  styleEl.textContent = css;
  document.head.appendChild(styleEl);
}
